// let Tables={
//     "component":"component",
// "draw":"draw",
// "drawCopy":"drawCopy",
// "questionDraw":"questionDraw",
// "tChapter":"tChapter",
// "tExamPaper":"tExamPaper",
// "tExamPaperAnswer":"tExamPaperAnswer",
// "tExamPaperQuestionCustomerAnswer":"tExamPaperQuestionCustomerAnswer",
// "tMessage":"tMessage",
// "tMessageUser":"tMessageUser",
// "tQuestion":"tQuestion",
// "tQuestion2":"tQuestion2",
// "tSubject":"tSubject",
// "tTaskExam":"tTaskExam",
// "tTaskExamCustomerAnswer":"tTaskExamCustomerAnswer",
// "tTextContent":"tTextContent",
// "tUser":"tUser",
// "tUserEventLog":"tUserEventLog",
// "tUserToken":"tUserToken",
// "tenant":"tenant",
// "tenantExamPaper":"tenantExamPaper",

// }

// let Tables={
//     "physicalTest":"physicalTest",
// "chapter":"chapter",
// "examPaper":"examPaper",
// "examPaperAnswer":"examPaperAnswer",
// "examPaperQuestionCustomerAnswer":"examPaperQuestionCustomerAnswer",
// "message":"message",
// "messageUser":"messageUser",
// "question":"question",
// "question2":"question2",
// "subject":"subject",
// "taskExam":"taskExam",
// "taskExamCustomerAnswer":"taskExamCustomerAnswer",
// "textContent":"textContent",
// "user":"user",
// "userEventLog":"userEventLog",
// "userToken":"userToken",
// "tenant":"tenant",
// "tenantExamPaper":"tenantExamPaper",

// }


let Tables={
    "physicalTest":"physicalTest",
"physical_test":"physical_test",
"physical_test":"physical_test",
"tChapter":"tChapter",
"chapter":"chapter",
"t_chapter":"t_chapter",
"tExamPaper":"tExamPaper",
"exam_paper":"exam_paper",
"t_exam_paper":"t_exam_paper",
"tExamPaperAnswer":"tExamPaperAnswer",
"exam_paper_answer":"exam_paper_answer",
"t_exam_paper_answer":"t_exam_paper_answer",
"tExamPaperQuestionCustomerAnswer":"tExamPaperQuestionCustomerAnswer",
"exam_paper_question_customer_answer":"exam_paper_question_customer_answer",
"t_exam_paper_question_customer_answer":"t_exam_paper_question_customer_answer",
"tMessage":"tMessage",
"message":"message",
"t_message":"t_message",
"tMessageUser":"tMessageUser",
"message_user":"message_user",
"t_message_user":"t_message_user",
"tQuestion":"tQuestion",
"question":"question",
"t_question":"t_question",
"tQuestion2":"tQuestion2",
"question_2":"question_2",
"t_question_2":"t_question_2",
"tSubject":"tSubject",
"subject":"subject",
"t_subject":"t_subject",
"tTaskExam":"tTaskExam",
"task_exam":"task_exam",
"t_task_exam":"t_task_exam",
"tTaskExamCustomerAnswer":"tTaskExamCustomerAnswer",
"task_exam_customer_answer":"task_exam_customer_answer",
"t_task_exam_customer_answer":"t_task_exam_customer_answer",
"tTextContent":"tTextContent",
"text_content":"text_content",
"t_text_content":"t_text_content",
"tUser":"tUser",
"user":"user",
"t_user":"t_user",
"tUserEventLog":"tUserEventLog",
"user_event_log":"user_event_log",
"t_user_event_log":"t_user_event_log",
"tUserToken":"tUserToken",
"user_token":"user_token",
"t_user_token":"t_user_token",
"tenant":"tenant",
"tenant":"tenant",
"tenant":"tenant",
"tenantExamPaper":"tenantExamPaper",
"tenant_exam_paper":"tenant_exam_paper",
"tenant_exam_paper":"tenant_exam_paper",

}




export default Tables
